### ISSUE TITLE
Angular 1.6

### ISSUE THREAD

**Issue by ravtakhar** [jonshaffer/angular-data-table#15]
I don't think this works with Angular 1.6

I get over 51 errors now... 'Cannot set property 'scrollBarWidth' of undefined'
...
'Cannot read property columns of undefined'
...

The only thing I did was upgrade from Angular 1.4 to Angular 1.6 
[Also checked for an updated version of this data-table]

Thanks!

**Comment by jonshaffer** [comment]
I'll be looking into the issue this week, would love to know if you have any updates. (Already looked at the CodePen change you mentioned in main repo)

**Comment by ravtakhar** [comment]
@jonshaffer Tried to make the actual fix myself... but couldn't figure it out (first time looking at the source code).

The this.options seems be undefined in transposeColumnDefaults. Thought it was issue so I tried to pass "options" through but later discovered that "columns" was undefined before even hitting that function. Sorry not much help, but I can look through the actual src code later this week if help is needed.

**Comment by jonshaffer** [comment]
@ravtakhar fix is in swimlane-1.6 branch on this project (which references swimlane master and not this forks master yet)

**Comment by ravtakhar** [comment]
@jonshaffer Thank you!

**Comment by jonshaffer** [comment]
Fixed with latest merge into this fork
