### ISSUE TITLE
Option for single sort not documented or in demo

### ISSUE THREAD

**Issue by adlaird** [jonshaffer/angular-data-table#31]
By default, multiple column sorting is turned on, so if one column is sorted, clicking on another column header adds a secondary sort to the table.  It exists in options.sortType but that isn't documented anywhere.

**Comment by adlaird** [comment]
This feature already exists.  If you add sortType: 'single' to the options configuration object for the grid then you get the functionality described in this enhancement.  This issue should be closed.

**Comment by jonshaffer** [comment]
That's cool, I'll reuse this issue for documentation since it is not in `src/defaults.js`, `README.md`, or `demos/sort.html`.

**Comment by adlaird** [comment]
I think this should now be closed

**Comment by jonshaffer** [comment]
Thanks! Added with release files for the config change
