### ISSUE TITLE
Output file "dataTable.js" is minified

### ISSUE THREAD

**Issue by nazar-kuzo** [jonshaffer/angular-data-table#88]
It would be great if you could update compiler config so output file "dataTable.js" would not be minified.

Thanks for your work!

**Comment by nazar-kuzo** [comment]
@BegeMode,

Seems like you are recently most active contributor, could you please look into it?

**Comment by BegeMode** [comment]
You can take dataTable.js without minification in my forked repository
https://github.com/begemode/angular-data-table

**Comment by nazar-kuzo** [comment]
@BegeMode, thanks, appreciate that!
